
    .first-feat-cat:hover img{
        opacity: 0.2;
    }
    .feat-cat1{
        margin-right: 0;
        box-sizing: border-box;
        flex-wrap: nowrap;
        padding: 4vw 16vw 0;

    }
    .best-price{
        padding-left: 0;

    }
    .best-price > img{
        width: 40vw;
        height: 100%;
    }
    .f-cat-body1{
        margin: 0;
        height: 100%;
        width: 20vw;
    }